name: Release creation flow
on:
  release:
    types: [published]

permissions:
  contents: read
  packages: read

jobs:
  build:
    uses: ./.github/workflows/_build.yaml

  test:
    needs: build
    uses: ./.github/workflows/_test.yaml

  sonar:
    needs: test
    uses: ./.github/workflows/_sonar.yaml
    secrets: inherit
    with:
      sonar-version: ${{ github.event.release.tag_name }}
      enforce-quality-gate: false

  build-push:
    needs: test
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-push.yaml
    with:
      tag: ${{ github.event.release.tag_name }}

  update-infra:
    needs: build-push
    uses: ./.github/workflows/_update-infra.yaml
    secrets: inherit
    with:
      environment: production
      tag: ${{ github.event.release.tag_name }}
